cmake_minimum_required(VERSION 4.2)
project(LearnOpenGL)
set(CACHE{CMAKE_C_EXTENSIONS} TYPE BOOL HELP "CMake: Enable compiler-specific extensions for C" VALUE OFF)
set(CACHE{CMAKE_CXX_EXTENSIONS} TYPE BOOL HELP "CMake: Enable compiler-specific extensions for C++" VALUE OFF)
include(CheckIPOSupported)
check_ipo_supported(RESULT IPOsupport LANGUAGES C CXX)
if(IPOsupport)
    set(CACHE{CMAKE_INTERPROCEDURAL_OPTIMIZATION} TYPE BOOL HELP "CMake: Enable link-time/interprocedural optimisation when not in Debug" VALUE ON)
    set(CACHE{CMAKE_INTERPROCEDURAL_OPTIMIZATION_DEBUG} TYPE BOOL HELP "CMake: Enable link-time/interprocedural optimisation when in Debug" VALUE OFF)
endif()
set(CACHE{FETCHCONTENT_QUIET} TYPE BOOL HELP "FetchContent: Enables QUIET option for all content population" VALUE OFF)
include(FetchContent)
set(CACHE{glfw_git_tag} TYPE STRING HELP "Git tag / branch / commit hash of GitHub repository glfw/glfw to use" VALUE 3.5.1)
set(CACHE{glad_git_tag} TYPE STRING HELP "Git tag / branch / commit hash of GitHub repository Dav1dde/glad to use" VALUE v2.0.8)
set(CACHE{stb_git_tag} TYPE STRING HELP "Git tag / branch / commit hash of GitHub repository nothings/stb to use" VALUE 2c980bb59875b0d32144a71867fbdebb2f77cd20)
#Note: "git_tag" is used here in the same sense as GIT_TAG in FetchContent_Declare, encompassing git tags, branches and commit hashes. Last I checked, the stb repo has no actual tags. Hence: commit hash
set(CACHE{stb_LICENSE_SHA256_HASH} TYPE STRING HELP "Expected SHA256 hash of nothings/stb/${stb_git_tag}/LICENSE" VALUE BEBFE904B14301657E4E5D655C811D51FD31B97C455B9CC2D8600D6BAC6CFF63)
set(CACHE{stb_stb_image.h_SHA256_HASH} TYPE STRING HELP "Expected SHA256 hash of nothings/stb/${stb_git_tag}/stb_image.h" VALUE 594C2FE35D49488B4382DBFAEC8F98366DEFCA819D916AC95BECF3E75F4200B3)
FetchContent_Declare(glfw GIT_REPOSITORY https://github.com/glfw/glfw GIT_TAG ${glfw_git_tag} GIT_PROGRESS ON)
FetchContent_Declare(glad GIT_REPOSITORY https://github.com/Dav1dde/glad GIT_TAG ${glad_git_tag} GIT_PROGRESS ON SOURCE_SUBDIR cmake)
option(GLFW_BUILD_DOCS "GLFW: Build the GLFW documentation" OFF)
option(GLFW_INSTALL "GLFW: Generate installation target" OFF)
FetchContent_MakeAvailable(glfw glad)
glad_add_library(glad_gl_33_core API gl:core=3.3 REPRODUCIBLE EXTENSIONS GL_KHR_debug)
set(stb_dir ${CMAKE_BINARY_DIR}/stb/)
message(STATUS "Attempting to download the stb headers LICENSE if it is not already present with the right SHA256 hash")
file(DOWNLOAD https://raw.githubusercontent.com/nothings/stb/${stb_git_tag}/LICENSE ${stb_dir}LICENSE SHOW_PROGRESS EXPECTED_HASH SHA256=${stb_LICENSE_SHA256_HASH})
message(STATUS "Attempting to download stb_image.h if it is not already present with the right SHA256 hash")
file(DOWNLOAD https://raw.githubusercontent.com/nothings/stb/${stb_git_tag}/stb_image.h ${stb_dir}include/stb/stb_image.h SHOW_PROGRESS EXPECTED_HASH SHA256=${stb_stb_image.h_SHA256_HASH})
file(WRITE ${stb_dir}src/stb_implementation.c "#include <stb/stb_image.h>")
add_library(stb)
target_compile_definitions(stb PRIVATE STB_IMAGE_IMPLEMENTATION)
target_sources(stb PRIVATE ${stb_dir}src/stb_implementation.c PUBLIC FILE_SET stb_headers TYPE HEADERS BASE_DIRS ${stb_dir}include FILES ${stb_dir}include/stb/stb_image.h)
set(CACHE{IDFK_PRIVATE_C_FLAGS} TYPE STRING HELP "C compiler flags to be used only when building the Idfk executable, not when building dependencies" VALUE)
set(CACHE{IDFK_PRIVATE_CXX_FLAGS} TYPE STRING HELP "C++ compiler flags to be used only when building the Idfk executable, not when building dependencies" VALUE)
set(CXX_EXTERN_C "extern \"C\"")#Added because I don't know how to use target_compile_definitions to define macros whose values have whitespace without making them string literals, beacuse that's what quoting the value does
set(CXX_EXTERN_C_BLOCK_START "extern \"C\" {")
set(CXX_EXTERN_C_BLOCK_END "}")
add_executable(Idfk)
target_compile_features(Idfk PRIVATE cxx_std_23)
target_compile_options(Idfk PRIVATE $<$<COMPILE_LANGUAGE:C>:${IDFK_PRIVATE_C_FLAGS}> $<$<COMPILE_LANGUAGE:CXX>:${IDFK_PRIVATE_CXX_FLAGS}>)
target_compile_definitions(Idfk PRIVATE GLFW_INCLUDE_NONE RESOURCE_DIR="${PROJECT_SOURCE_DIR}/"
    $<$<COMPILE_LANGUAGE:C>:EXTERN_C EXTERN_C_BLOCK_START EXTERN_C_BLOCK_END>
    $<$<COMPILE_LANGUAGE:CXX>:EXTERN_C=${CXX_EXTERN_C} EXTERN_C_BLOCK_START=${CXX_EXTERN_C_BLOCK_START} EXTERN_C_BLOCK_END=${CXX_EXTERN_C_BLOCK_END}>)
target_link_libraries(Idfk PRIVATE glfw glad_gl_33_core stb)
target_sources(Idfk PRIVATE main.cpp GLFWCallbacks.cpp OpenGLCallbacks.cpp OGLShaderAbstraction.cpp)